spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    application:
      name: service-programdept
    servlet:
      multipart:
        max-file-size: 50000Mb
        max-request-size: 50000Mb
        enabled: true
server:
    port: 8080
    max-http-header-size: 100000

hive:
  url: jdbc:hive2://192.168.192.101:10000/default
  driver-class-name: org.apache.hive.jdbc.HiveDriver
  type: com.alibaba.druid.pool.DruidDataSource
  user: root
  password: 123456
  initialSize: 1
  minIdle: 3
  maxActive: 20
  maxWait: 6000000
  timeBetweenEvictionRunsMillis: 6000000
  minEvictableIdleTimeMillis: 30000
  validationQuery: select 1
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
hive1:
  url: jdbc:hive2://192.168.192.101:10000/job_post
  driver-class-name: org.apache.hive.jdbc.HiveDriver
  type: com.alibaba.druid.pool.DruidDataSource
  user: root
  password: 123456
  initialSize: 1
  minIdle: 3
  maxActive: 20
  maxWait: 6000000
  timeBetweenEvictionRunsMillis: 6000000
  minEvictableIdleTimeMillis: 30000
  validationQuery: select 1
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20



